<div class="megamenu-no-items">
	<em><?php echo __( 'No submenu items found ...', 'thrive-cb' ); ?></em>
	<div class="m-info">
		<?php echo __( 'In order to populate the megamenu, use a menu that has 3rd level menu items. ', 'thrive-cb' ); ?>
		<span class="h-link" onclick="window.open('https://thrivethemes.com/tkb_item/how-do-mega-menus-work/', '_blank');"><?php echo __( 'Learn more', 'thrive-cb' ); ?></span>
	</div>
</div>