<div class="control-grid no-space pb-5">
	<span class="label"><#= this.model.config.label #></span>
	<div class="link-tabs no-space justify-start"></div>
</div>
<div class="link-boxes">
	<div data-tab="link" style="display: none;">
		<div class="image-link-box">
			<div class="control-grid no-space image-link">
				<div id="tcb-link-search-control" class="fill pt-0"></div>
				<a href="javascript:void(0)" class="click flex-mid ml-5" data-fn="open_link_search_settings"><?php tcb_icon( 'settings' ); ?></a>
			</div>
			<div class="image-link tcb-flex space-between">
				<div class="elem-link-newtab"></div>
				<div class="elem-link-nofollow"></div>
			</div>
		</div>
	</div>
	<div data-tab="jump" style="display: none;">

		<div class="tve-jump-smooth-anim"></div>
		<div class="tcb-jump-target-box control-grid">
			<span><?php echo __( 'Target', 'thrive-cb' ); ?></span>
			<a id="tcb-jump-target" class="click" data-fn="scrollTo"></a>
		</div>
		<div id="tcb-jumplink-buttons" class="tcb-flex space-between">
			<div id="select-target" class="tve-button click" data-fn="selectJumpTarget"><?php echo __( 'Select Target', 'thrive-cb' ); ?></div>
			<div id="remove-target" class="tve-button tve-remove click" data-fn="removeJumpTarget"><?php echo __( 'Remove Target', 'thrive-cb' ); ?></div>
			<div id="modify-target" class="tve-button click" data-fn="modifyJumpTarget"><?php echo __( 'Modify Target', 'thrive-cb' ); ?></div>
		</div>

	</div>
</div>
